### ISSUE TITLE
[Bug] Console Error - Entity threw exception at world

### ISSUE THREAD

**Issue by Danila767** [SeanOMik/TamableFoxes#101]
```
Entity threw exception at world:1557.7125856769637,73.0,-2767.7732766513273
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityLiving.ct()" because the return value of "net.seanomik.tamablefoxes.versions.version_1_20_R1.EntityTamableFox.getOwner()" is null
        at net.seanomik.tamablefoxes.versions.version_1_20_R1.EntityTamableFox.a(EntityTamableFox.java:577) ~[TamableFoxes_v2.2.10-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1527) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.hurt(Animal.java:87) ~[?:?]
        at net.minecraft.world.entity.animal.Wolf.doHurtTarget(Wolf.java:323) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:130) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:121) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:157) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:920) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3373) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:675) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:155) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:63) ~[?:?]
        at net.minecraft.world.entity.animal.Wolf.aiStep(Wolf.java:186) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3028) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:437) ~[?:?]
        at net.minecraft.world.entity.animal.Wolf.tick(Wolf.java:202) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1368) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:875) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:852) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-17]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

MC: git-Pufferfish-17 (MC: 1.20.1)
Java: java 18

**Comment by SeanOMik** [comment]
Just make a [release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.11-SNAPSHOT) fixing this, it was a pretty simple fix. Thanks for the bug report!
