### ISSUE TITLE
I can't tame foxes

### ISSUE THREAD

**Issue by Villwulf** [SeanOMik/TamableFoxes#106]
Hello, first of all, thank you for the plugin.

I am starting the plugin on a mohist server. I only have two plugins TamableFoxes and gsit.

No matter how much I try to feed the foxes with berries they are never tamed.

I already spent like 3 stacks of glow berries and nothing.

I have also changed the following in the config.yml:
`max-fox-tames: 3`

This change caused me this error in the console:

`
[14:36:52 INFO]: [Tamablefoxes] Loading Tamablefoxes v2.2.11-SNAPSHOT
[14:36:52 INFO]: [Tamable Foxes] Registering entity for MC Version v1_20_R1...
[14:36:52 INFO]: [Tamable Foxes] Replaced tamable fox entity!
[14:36:52 WARN]: java.sql.SQLException: No suitable driver found for jdbc:sqlite:C:\Users\Villwulf\Desktop\mohist\plugins\Tamablefoxes/userFoxAmount.db
[14:36:52 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:708)
[14:36:52 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
[14:36:52 WARN]:        at net.seanomik.tamablefoxes.util.io.sqlite.SQLiteHandler.connect(SQLiteHandler.java:30)
[14:36:52 WARN]:        at net.seanomik.tamablefoxes.util.io.sqlite.SQLiteHandler.connect(SQLiteHandler.java:24)
[14:36:52 WARN]:        at net.seanomik.tamablefoxes.util.io.sqlite.SQLiteHelper.createTablesIfNotExist(SQLiteHelper.java:37)
[14:36:52 WARN]:        at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:108)
[14:36:52 WARN]:        at TRANSFORMER/forge@47.1.76/org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:436)
[14:36:52 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:211)
[14:36:52 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:851)
[14:36:52 WARN]:        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:279)
[14:36:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[14:36:52 ERROR]: Cannot invoke "java.sql.Connection.getMetaData()" because the return value of "net.seanomik.tamablefoxes.util.io.sqlite.SQLiteHandler.getConnection()" is null initializing Tamablefoxes v2.2.11-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.getMetaData()" because the return value of "net.seanomik.tamablefoxes.util.io.sqlite.SQLiteHandler.getConnection()" is null
        at net.seanomik.tamablefoxes.util.io.sqlite.SQLiteHelper.createTablesIfNotExist(SQLiteHelper.java:39) ~[?:?]
        at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:108) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:436) ~[forge-1.20.1-47.1.76-universal.jar%23212!/:6b34da8f-db4ba2897-d2eba2c8-47.4.47]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:211) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:851) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:279) ~[server-1.20.1-20230612.114412-srg.jar%23207!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
        
[14:36:52 INFO]: [Tamablefoxes] Enabling Tamablefoxes v2.2.11-SNAPSHOT
`

If you need any additional information about the server, I will gladly share it here.

Greetings and thank you

**Comment by SeanOMik** [comment]
Hm, its weird that changing the configuration caused the error; I think that's unrelated though. You need to use raw chicken, not berries

**Comment by Villwulf** [comment]
True, I can tame foxes with raw chicken, I was getting confused about the object. But if I change the maximum in the config file I get that error
