### ISSUE TITLE
Encountered an unexpected exception java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by Japerz12138** [SeanOMik/TamableFoxes#19]
When I let fox sit, and generate a chicken near by, the server crashes.
Using Spigot-1.16.1!

Error code is below:
`[15:51:00 ERROR]: Encountered an unexpected exception
java.lang.StackOverflowError: null
        at net.minecraft.server.v1_16_R1.ItemMonsterEgg.a(ItemMonsterEgg.java:105) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.ItemMonsterEgg.a(ItemMonsterEgg.java:125) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.EntityInsentient.c(EntityInsentient.java:1173) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.EntityInsentient.a(EntityInsentient.java:1137) ~[patched_1.16.1.jar:git-Paper-135]
        at net.seanomik.tamablefoxes.versions.version_1_16_R1.EntityTamableFox.b(EntityTamableFox.java:250) ~[?:?]
        at net.minecraft.server.v1_16_R1.EntityInsentient.a(EntityInsentient.java:1142) ~[patched_1.16.1.jar:git-Paper-135]
        at net.seanomik.tamablefoxes.versions.version_1_16_R1.EntityTamableFox.b(EntityTamableFox.java:250) ~[?:?]`

Thank You.

**Comment by SeanOMik** [comment]
I'll take a look at it tomorrow. Thanks for creating an issue!

**Comment by Japerz12138** [comment]
Got it! Keep up the good work! I really like having little foxes around me, and the players on my server also like it very much. Thank you for making the fox so cute in Minecraft!

**Comment by Japerz12138** [comment]
Oh wait a sec! I double checked my core, I'm actually using Paper 1.16.1!

**Comment by SeanOMik** [comment]
Does the crash happen when you right click a fox with a chicken spawn egg? 

I wasn't able to get a crash when I was spawning the chicken a few blocks away, but I was when I right clicked on the fox.

**Comment by Japerz12138** [comment]
I tested it again! Confirmed that it was a crash caused by right click a fox with a chicken spawn egg!

**Comment by SeanOMik** [comment]
Awesome! I'm gonna push the code and create a new release then.

**Comment by Japerz12138** [comment]
Got it! Thank You!

**Comment by SeanOMik** [comment]
[Here's the new release](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.7.3-SNAPSHOT). Thanks for making an issue and being so easy to work with, enjoy!

**Comment by Japerz12138** [comment]
Awesome! Thank you so much for your work! Love this plugin <3
