### ISSUE TITLE
Can't tame foxes

### ISSUE THREAD

**Issue by dandud100** [SeanOMik/TamableFoxes#41]
My Server Version: 
This server is running Paper version git-Paper-675 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-670 (MC: 1.16.5)

On Startup i get this error:
[20:01:05 INFO]: [Tamable Foxes] Registering entity for MC Version v1_16_R3...
[20:01:06 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Tamablefoxes v1.9.1-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at net.seanomik.tamablefoxes.versions.version_1_16_R3.NMSInterface_1_16_R3.registerCustomFoxEntity(NMSInterface_1_16_R3.java:23) ~[?:?]
        at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-675]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @532ad4e5
        at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:25) ~[?:?]
        ... 7 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @532ad4e5
        at java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:260) ~[?:?]
        at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:22) ~[?:?]
        ... 7 more

When i rightclick a fox with raw chicken nothing happens. Please fix this.

**Comment by SeanOMik** [comment]
What Java version is your server running on?

**Comment by dandud100** [comment]
Java SE Development Kit 16.0.1

**Comment by dandud100** [comment]
System Info: Java 16 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24) Host: Windows 10 10.0 (amd64)

**Comment by SeanOMik** [comment]
Whats your start script for your server?

**Comment by dandud100** [comment]
`@ECHO OFF
title [Minecraft Server]
color 03
java -Xms2G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar minecraft.jar nogui`

**Comment by dandud100** [comment]
`
@ECHO OFF
title [Minecraft Server]
color 03
java -Xms2G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar minecraft.jar nogui
`

**Comment by dandud100** [comment]
> @ECHO OFF
title [Minecraft Server]
color 03
java -Xms2G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar minecraft.jar nogui

**Comment by dandud100** [comment]
@ECHO OFF
title [Minecraft Server]
color 03
java -Xms2G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar minecraft.jar nogui

**Comment by SeanOMik** [comment]
Try to make this your start script:
```
@echo OFF
title [Minecraft Server]
color 03
java -Xms2G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED -jar minecraft.jar nogui
```

**Comment by SeanOMik** [comment]
Closed due to inactivity
