### ISSUE TITLE
Spigot and PaperMC servers with old TamableFoxes configuration files crash

### ISSUE THREAD

**Issue by Vulpovile** [SeanOMik/TamableFoxes#42]
[02:35:26] [Server thread/INFO]: [Tamablefoxes] Loading Tamablefoxes v1.9.1-SNAPSHOT
[02:35:26] [Server thread/WARN]: [Tamablefoxes] Could not save language.yml to plugins/Tamablefoxes/language.yml because language.yml already exists.
[02:35:26] [Server thread/WARN]: [Tamablefoxes] Could not save language.yml to plugins/Tamablefoxes/language.yml because language.yml already exists.
[02:35:26] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Tamablefoxes v1.9.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
at net.seanomik.tamablefoxes.io.LanguageConfig.getString(LanguageConfig.java:82) ~[?:?]
at net.seanomik.tamablefoxes.io.LanguageConfig.getMCVersionLoading(LanguageConfig.java:87) ~[?:?]
at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:61) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-732]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-732]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-732]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-732]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

(on paper)

**Comment by SeanOMik** [comment]
Delete the old language.yml file.
