### ISSUE TITLE
Error initializing in purpur (paper fork)

### ISSUE THREAD

**Issue by Yufukuai** [SeanOMik/TamableFoxes#45]
- Hello, I am trying to use this plugin but when I try to start my server with this plugin, it doesn't load properly and when trying to spawn a tamable fox it gives errors

### The error at startup:

```
[org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Tamablefoxes v1.9.1-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:184) ~[?:?]
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173) ~[?:?]
        at net.seanomik.tamablefoxes.versions.version_1_16_R3.NMSInterface_1_16_R3.registerCustomFoxEntity(NMSInterface_1_16_R3.java:23) ~[?:?]
        at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:263) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3154/0x00000000ba5dfc38.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:853) [?:?]
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: The package: java.lang.reflect containing the target class is not opened to the module: <null>
        at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:25) ~[?:?]
        ... 8 more
Caused by: java.lang.IllegalAccessException: The package: java.lang.reflect containing the target class is not opened to the module: <null>
        at java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:2246) ~[?:?]
        at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:22) ~[?:?]
        ... 8 more
```

### The error when trying to spawn foxes:

```
[21:27:04 WARN]: java.lang.ClassCastException: net.minecraft.server.v1_16_R3.EntityFox incompatible with net.seanomik.tamablefoxes.versions.version_1_16_R3.EntityTamableFox
[21:27:04 WARN]:        at net.seanomik.tamablefoxes.versions.version_1_16_R3.NMSInterface_1_16_R3.spawnTamableFox(NMSInterface_1_16_R3.java:33)
[21:27:04 WARN]:        at net.seanomik.tamablefoxes.CommandSpawnTamableFox.onCommand(CommandSpawnTamableFox.java:49)
[21:27:04 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:27:04 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[21:27:04 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2286)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2101)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2054)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$7375/0x00000000c5539d08.run(Unknown Source)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1326)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1319)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1295)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[21:27:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3154/0x00000000ba5dfc38.run(Unknown Source)
[21:27:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:853)
```

- I hope this can be solved :D

**Comment by SeanOMik** [comment]
What Java version is your server running on?

**Comment by Yufukuai** [comment]
Java 16 (Eclipse OpenJ9 VM openj9-0.26.0)

**Comment by SeanOMik** [comment]
Try to add ```
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED```
to your program arguments.

**Comment by Yufukuai** [comment]
That should go in the server start script?

**Comment by SeanOMik** [comment]
Yeah. Show me your current server start script

**Comment by Yufukuai** [comment]
Here 
![image](https://user-images.githubusercontent.com/57686158/121601771-6655fc80-ca14-11eb-86d4-29eb17cd53d6.jpeg)

**Comment by SeanOMik** [comment]
change it to ```
java -Xmx4096M -Xms3072M --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED -jar purpurclip-1.16.5-1051.jar nogui```

**Comment by Yufukuai** [comment]
It worked, thank you!
