### ISSUE TITLE
WARNs at boot on 1.16.5

### ISSUE THREAD

**Issue by joex92** [SeanOMik/TamableFoxes#46]
The plugin seems to works fine, but I get this WARNS at boot:
```apache
[13:58:22] [Server thread/INFO]: [Tamablefoxes] Loading Tamablefoxes v1.9.2-SNAPSHOT
[13:58:22] [Server thread/WARN]: [Tamablefoxes] Could not save language.yml to plugins/Tamablefoxes/language.yml because language.yml already exists.
[13:58:22] [Server thread/INFO]: [Tamable Foxes] Registering entity for MC Version v1_16_R3...
[13:58:22] [Server thread/INFO]: [Tamable Foxes] Failed to replace tamable fox entity!
[13:58:22] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers
[13:58:22] [Server thread/WARN]: at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[13:58:22] [Server thread/WARN]: at net.seanomik.tamablefoxes.versions.FieldHelper.makeNonFinal(FieldHelper.java:17)
[13:58:22] [Server thread/WARN]: at net.seanomik.tamablefoxes.versions.FieldHelper.setField(FieldHelper.java:29)
[13:58:22] [Server thread/WARN]: at net.seanomik.tamablefoxes.versions.version_1_16_R3.NMSInterface_1_16_R3.registerCustomFoxEntity(NMSInterface_1_16_R3.java:23)
[13:58:22] [Server thread/WARN]: at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:62)
[13:58:22] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394)
[13:58:22] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:274)
[13:58:22] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[13:58:22] [Server thread/WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[13:58:22] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
[13:58:22] [Server thread/INFO]: [Tamable Foxes] Replaced tamable fox entity!
```

**Comment by SeanOMik** [comment]
Thats weird that its showing as a warning since it reads as a error's stacktrace. Could you try the previous [version `1.9.1`](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.9.1-SNAPSHOT)?

**Comment by joex92** [comment]
> Thats weird that its showing as a warning since it reads as a error's stacktrace. Could you try the previous [version `1.9.1`](https://github.com/SeanOMik/TamableFoxes/releases/tag/1.9.1-SNAPSHOT)?

```
[17:03:02] [Server thread/INFO]: [Tamablefoxes] Loading Tamablefoxes v1.9.1-SNAPSHOT
[17:03:02] [Server thread/WARN]: [Tamablefoxes] Could not save language.yml to plugins/Tamablefoxes/language.yml because language.yml already exists.
[17:03:02] [Server thread/WARN]: [Tamablefoxes] Could not save language.yml to plugins/Tamablefoxes/language.yml because language.yml already exists.
[17:03:02] [Server thread/INFO]: [Tamable Foxes] Registering entity for MC Version v1_16_R3...
[17:03:02] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Tamablefoxes v1.9.1-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
at net.seanomik.tamablefoxes.versions.version_1_16_R3.NMSInterface_1_16_R3.registerCustomFoxEntity(NMSInterface_1_16_R3.java:23) ~[?:?]
at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:62) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:274) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @7e49911
at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:25) ~[?:?]
... 7 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @7e49911
at java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:260) ~[?:?]
at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:22) ~[?:?]
... 7 more
```

**Comment by SeanOMik** [comment]
Try to add 
```
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED```
to your program arguments in your start script.

**Comment by joex92** [comment]
> Try to add
> 
> ```
> --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED```
> to your program arguments in your start script.
> ```

can't... the host doesn't allow me to add more arguments, only to use the ones that it gives me...

**Comment by joex92** [comment]
I can't access the load script, tried loading it but it didn´t work... so I´m going back to the prev build... 

```
15.06 22:12:39 [Server] ERROR Could not load 'plugins/TamableFoxes_v1.9.2.1-SNAPSHOT.jar' in folder 'plugins'
15.06 22:12:39 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
15.06 22:12:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
15.06 22:12:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
15.06 22:12:39 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
15.06 22:12:39 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
15.06 22:12:39 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1078) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
15.06 22:12:39 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
15.06 22:12:39 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
15.06 22:12:39 [Server] INFO Caused by: java.util.zip.ZipException: zip END header not found
15.06 22:12:39 [Server] INFO at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1441) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.zip.ZipFile$Source.get(ZipFile.java:1225) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:240) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:171) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
15.06 22:12:39 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:285) ~[?:?]
15.06 22:12:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-120]
15.06 22:12:39 [Server] INFO ... 6 more
```

**Comment by SeanOMik** [comment]
If you can't edit the start script then you need to use an older Java version or contact your host to see if they'll be willing to change it for you.

Also in that error, you seem to be using the newest version

**Comment by joex92** [comment]
hmm... ok... I´ll try asking on my hosting support if they can add those parameters... would those parameters will be useful for other plugins? 
Also isn´t there a way for the plugin to work properly without those parameters?

**Comment by SeanOMik** [comment]
> Also isn´t there a way for the plugin to work properly without those parameters?

Unless you use a Java version older than Java 16, no. The reason you have to add those is due to updates in Java 16 that cause anything outside of the standard library to not be allowed to use reflection on classes from the standard library. The plugin uses reflection on a standard library class so it can set a `private final` field (by first making it non-final).

**Comment by joex92** [comment]
oh ok, but that wouldn´t affect other plugins, right?

**Comment by SeanOMik** [comment]
No, it shouldn't.

**Comment by joex92** [comment]
well... I fixed it... kinda... I went back to Java11 because my hosting won't allow me to add arguments for security reasons... 
anyways thanks... 

I´ll close this by saying to whoever comes here: "go back to Java11 if your server is not 1.17+"
