### ISSUE TITLE
Error. Plugin don`t start.

### ISSUE THREAD

**Issue by Futodama** [SeanOMik/TamableFoxes#50]
[15:13:55] [Server thread/INFO]: [Tamablefoxes] Loading Tamablefoxes v1.9.2.1-SNAPSHOT
[15:13:55] [Server thread/WARN]: [Tamablefoxes] Could not save language.yml to plugins\Tamablefoxes\language.yml because language.yml already exists.
[15:13:55] [Server thread/WARN]: [Tamablefoxes] Could not save language.yml to plugins\Tamablefoxes\language.yml because language.yml already exists.
[15:13:55] [Server thread/INFO]: [Tamable Foxes] Registering entity for MC Version v1_16_R3...
[15:13:55] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Tamablefoxes v1.9.2.1-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at net.seanomik.tamablefoxes.versions.version_1_16_R3.NMSInterface_1_16_R3.registerCustomFoxEntity(NMSInterface_1_16_R3.java:23) ~[?:?]
	at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:62) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-775]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-775]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-775]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-775]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @245027f5
	at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:25) ~[?:?]
	... 7 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @245027f5
	at java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:260) ~[?:?]
	at net.seanomik.tamablefoxes.versions.FieldHelper.<clinit>(FieldHelper.java:22) ~[?:?]

**Comment by SeanOMik** [comment]
Did you read the [note on the readme](https://github.com/SeanOMik/TamableFoxes#note-if-you-are-running-java-16-you-need-to-add-some-stuff-to-your-program-arguments-in-your-server-start-script)?

**Comment by Plasman888** [comment]
When i add that, the bat file just doesnt work anymore

**Comment by SeanOMik** [comment]
Send me the text in the bat file

**Comment by Plasman888** [comment]
java -Xms512M -Xmx16G -jar serverspigot.jar --nogui --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED

**Comment by SeanOMik** [comment]
Try this:
```
java -Xms512M -Xmx16G --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED -jar serverspigot.jar --nogui
```

**Comment by Plasman888** [comment]
Nope still doesnt work

**Comment by Plasman888** [comment]
i removed the ''' at the back n now it works

**Comment by Plasman888** [comment]
thx

**Comment by SeanOMik** [comment]
Oh sorry, I forgot that that has to be put at the start of the next line in GitHub. Anyway, glad that its working now. Have fun!
