### ISSUE TITLE
I Can't Tame them

### ISSUE THREAD

**Issue by NieXavosao** [SeanOMik/TamableFoxes#54]
idk why but i'm using the command /spawntamablefox and I can't get any of them

**Comment by SeanOMik** [comment]
Do you have any errors in the console?

**Comment by NieXavosao** [comment]
[16:41:50 INFO]: __Nie issued server command: /spawntamablefox red
[16:41:50 WARN]: java.lang.ClassCastException: class net.minecraft.entity.passive.FoxEntity cannot be cast to class net.seanomik.tamablefoxes.versions.version_1_16_R3.EntityTamableFox (net.minecraft.entity.passive.FoxEntity is in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @19bfbe28; net.seanomik.tamablefoxes.versions.version_1_16_R3.EntityTamableFox is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4c805ae5)
[16:41:50 WARN]:        at net.seanomik.tamablefoxes.versions.version_1_16_R3.NMSInterface_1_16_R3.spawnTamableFox(NMSInterface_1_16_R3.java:34)
[16:41:50 WARN]:        at net.seanomik.tamablefoxes.CommandSpawnTamableFox.onCommand(CommandSpawnTamableFox.java:42)
[16:41:50 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:41:50 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157)
[16:41:50 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:767)
[16:41:50 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1888)
[16:41:50 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1730)
[16:41:50 WARN]:        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39)
[16:41:50 WARN]:        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10)
[16:41:50 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28)
[16:41:50 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[16:41:50 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152)
[16:41:50 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[16:41:50 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899)
[16:41:50 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179)
[16:41:50 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125)
[16:41:50 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882)
[16:41:50 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876)
[16:41:50 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:135)
[16:41:50 WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:862)
[16:41:50 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:782)
[16:41:50 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283)
[16:41:50 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by SeanOMik** [comment]
Are you using any mods? I see this in the log: `cpw.mods.modlauncher.TransformingClassLoader`

**Comment by NieXavosao** [comment]
yeah, i'm using something like 80 mods

**Comment by SeanOMik** [comment]
Well, it looks like it has something to do with a mod. Are there any creature mods installed, or something that may mess with the fox entity?

**Comment by NieXavosao** [comment]
I dont have any creature mod, and I dont think I have some mod that mess with fox fr

**Comment by SeanOMik** [comment]
Could you send the whole server log?

**Comment by SeanOMik** [comment]
This will be closed soon due to inactivity
