### ISSUE TITLE
1.18 Incompatibility

### ISSUE THREAD

**Issue by pokemonrocks9** [SeanOMik/TamableFoxes#67]
Wanted to note here the plugin will not load on 1.18 Paper. 
error
[org.bukkit.craftbukkit.v1_18_R1.CraftServer] Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null initializing Tamablefoxes v2.1.6-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null
	at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:73) ~[TamableFoxes_v2.1.6-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.18.jar:git-Paper-"1f5b013"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.jar:git-Paper-"1f5b013"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-"1f5b013"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-"1f5b013"]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by SeanOMik** [comment]
To be honest, didn't even know 1.18 was released. Unfortunately, I won't have time to work on it until next weekend (after dec 10th) since I have finals all week, sorry!

**Comment by pokemonrocks9** [comment]
All good. I'll keep an eye out for it. Good luck on your finals!

**Comment by Futodama** [comment]
"Привет! Я знаю что ты сможешь поработать над плагином только после 10 декабря. Однако возможно данный текст ошибки тебе также поможет. Он новее. " - Оригинал (original).

"Hi! I know that you will be able to work on the plugin only after December 10th. However, perhaps this error text will also help you. It's newer." - translate.

[23:49:07] [Server thread/INFO]: [Fox] You're trying to run MC version 1.18 which is not supported!
[23:49:07] [Server thread/INFO]: [Fox] Registering entity for MC Version v1_18_R1...
[23:49:07] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null initializing Tamablefoxes v2.1.6-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null
	at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:73) ~[TamableFoxes_v2.1.6-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.18.jar:git-Paper-58]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-58]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-58]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by SeanOMik** [comment]
Just updated to 1.18! Check the [latest release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.0-SNAPSHOT), have fun!
