### ISSUE TITLE
Error in console on 1.18.1

### ISSUE THREAD

**Issue by pokemonrocks9** [SeanOMik/TamableFoxes#68]
**Describe the bug**

Error in console on load

**To Reproduce**
1. Place [...]
2. Take [...]
3. Click on [...] then [...]
Unknown but happens on launch
**Expected behavior**

**Errors**
If any errors or stack traces appeared in the console, please link to them here. Please use Pastebin to post stack traces. Don't paste them into the issue.
[00:24:10] [Server thread/INFO]: [Tamablefoxes] Loading Tamablefoxes v2.2.0-SNAPSHOT
[00:24:10] [Server thread/INFO]: [Tamable Foxes] ERROR: This plugin version only supports Spigot 1.14-1.16.4! Not registering entity! Make sure your Java version is no newer than Java 11!
[00:24:10] [Server thread/INFO]: [Tamable Foxes] You're trying to run MC version 1.18.1 which is not supported!
[00:24:10] [Server thread/INFO]: [Tamable Foxes] Registering entity for MC Version v1_18_R1...
[00:24:10] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null initializing Tamablefoxes v2.2.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null
	at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:77) ~[TamableFoxes_v2.2.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.18.1.jar:git-Paper-"901fd94"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-"901fd94"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-"901fd94"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-"901fd94"]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
**Screenshots**

**Versions**
MC: 1.18.1 (Paper 901fd94)
Java: Unknown (Remote Host)

**Additional context**
Happens on launch and stops the plugin from loading

**Comment by femboyfin** [comment]
Having the same issue, here's my test using a fresh 'install' of the latest Paper build with only Tamablefoxes.
<details>
  <summary>latest.log</summary>

```
[22:39:16] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:39:16] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[22:39:16] [ServerMain/INFO]: Reloading ResourceManager: Default, bukkit
[22:39:16] [Worker-Main-6/INFO]: Loaded 7 recipes
[22:39:18] [Server thread/INFO]: Starting minecraft server version 1.18.1
[22:39:18] [Server thread/INFO]: Loading properties
[22:39:18] [Server thread/INFO]: This server is running Paper version git-Paper-69 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 29bd57b)
[22:39:18] [Server thread/INFO]: Server Ping Player Sample Count: 12
[22:39:18] [Server thread/INFO]: Using 4 threads for Netty based IO
[22:39:18] [Server thread/INFO]: Default game type: SURVIVAL
[22:39:18] [Server thread/INFO]: Generating keypair
[22:39:18] [Server thread/INFO]: Starting Minecraft server on *:25565
[22:39:18] [Server thread/INFO]: Using default channel type
[22:39:18] [Server thread/INFO]: Paper: Using Java 11 compression from Velocity.
[22:39:18] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[22:39:18] [Server thread/INFO]: [Tamablefoxes] Loading Tamablefoxes v2.2.0-SNAPSHOT
[22:39:18] [Server thread/INFO]: [Tamable Foxes] ERROR: This plugin version only supports Spigot 1.14-1.16.4! Not registering entity! Make sure your Java version is no newer than Java 11!
[22:39:18] [Server thread/INFO]: [Tamable Foxes] You're trying to run MC version 1.18.1 which is not supported!
[22:39:18] [Server thread/INFO]: [Tamable Foxes] Registering entity for MC Version v1_18_R1...
[22:39:18] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null initializing Tamablefoxes v2.2.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null
	at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:77) ~[TamableFoxes_v2.2.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-69]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-69]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:39:18] [Server thread/INFO]: [Tamablefoxes] Enabling Tamablefoxes v2.2.0-SNAPSHOT
[22:39:18] [Server thread/INFO]: [Tamable Foxes] This plugin version only supports Spigot 1.14-1.16.4! Disabling plugin! Make sure your Java version is no newer than Java 11!
[22:39:18] [Server thread/INFO]: [Tamablefoxes] Disabling Tamablefoxes v2.2.0-SNAPSHOT
[22:39:18] [Server thread/INFO]: [Tamable Foxes] Saving foxes.
[22:39:18] [Server thread/INFO]: Preparing level "world"
[22:39:22] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[22:39:22] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[22:39:22] [Server thread/INFO]: Time elapsed: 274 ms
[22:39:22] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[22:39:23] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[22:39:23] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[22:39:23] [Server thread/INFO]: Time elapsed: 541 ms
[22:39:23] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[22:39:23] [Worker-Main-3/INFO]: Preparing spawn area: 2%
[22:39:23] [Server thread/INFO]: Time elapsed: 439 ms
[22:39:23] [Server thread/INFO]: Running delayed init tasks
[22:39:23] [Server thread/INFO]: Done (5.910s)! For help, type "help"
[22:39:23] [Server thread/INFO]: Timings Reset
[22:39:25] [Server thread/INFO]: Checking version, please wait...
[22:39:26] [Thread-12/INFO]: This server is running Paper version git-Paper-69 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 29bd57b)
You are running the latest version
[22:39:28] [Server thread/INFO]: Tamablefoxes version 2.2.0-SNAPSHOT
[22:39:28] [Server thread/INFO]: Adds tamable foxes to Minecraft!
[22:39:30] [Server thread/INFO]: Stopping the server
[22:39:30] [Server thread/INFO]: Stopping server
[22:39:30] [Server thread/INFO]: Saving players
[22:39:30] [Server thread/INFO]: Saving worlds
[22:39:30] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[22:39:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[22:39:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[22:39:35] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:39:35] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:39:35] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:39:35] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[22:39:35] [Server thread/INFO]: Flushing Chunk IO
[22:39:35] [Server thread/INFO]: Closing Thread Pool
[22:39:35] [Server thread/INFO]: Closing Server
```

</details>

**Versions** 
MC: 
```
This server is running Paper version git-Paper-69 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 29bd57b)
```

Java: 
```
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

**Additional context**
This was tested on my personal machine running the latest Windows 11 Version 21H2 (OS Build 22000.348). Also I checked and it does create the `plugins/Tamablefoxes` folder with a correct `language.yml` within it.

**Comment by SeanOMik** [comment]
Oh I didn't think about 1.18.1. Give me a moment

**Comment by SeanOMik** [comment]
@pokemonrocks9 @bigfinfrank just made a [release for 1.18.1](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.1-SNAPSHOT).

If you run into any errors, just tell me
