### ISSUE TITLE
Not working on Paper (or Spigot) 1.15.2

### ISSUE THREAD

**Issue by Pecacheu** [SeanOMik/TamableFoxes#7]
Tried Paper and Spigot as well. I'm getting this error on startup:
```
[23:28:26 WARN]: [Tamablefoxes] Could not save language.yml to plugins/Tamablefoxes/language.yml because language.yml already exists.
[23:28:26 WARN]: [Tamablefoxes] Could not save language.yml to plugins/Tamablefoxes/language.yml because language.yml already exists.
[23:28:26 WARN]: java.lang.NoSuchFieldException: modifiers
[23:28:26 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
[23:28:26 WARN]:        at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:68)
[23:28:26 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:361)
[23:28:26 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:227)
[23:28:26 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[23:28:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:830)
[23:28:26 INFO]: [Tamable Foxes] Failed to replace tamable fox entity!
```

Also nothing seems to change in game. Foxes behave normally and they don't do anything when given chicken.

**Comment by SeanOMik** [comment]
What java version are you using? Run `java -version` in cmd

**Comment by Pecacheu** [comment]
It's Java 13 on Linux x86_64. I know it's definitely the latest because one plugin I use recently demanded to be run on Java 11 or newer and my Java was super out of date, so I updated it just a few days ago.

```
Java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing
```

**Comment by SeanOMik** [comment]
That's weird, I just installed 13.0.2 and the de compiled code shows that field running. Try java 11 instead and tell me what comes of that

**Comment by Pecacheu** [comment]
Huh seems to work with Java 8 on my Windows machine, but not Java 13. Also tested with Java 13 on my Windows PC and same error as on Linux. With Java 8 the output was: `[Tamable Foxes] Replaced tamable fox entity!`

I can try Java 11 in a bit.

**Comment by SeanOMik** [comment]
Okay, it seems like its an issue with Java 13 then, maybe even Java 12.

**Comment by Pecacheu** [comment]
Welp never mind on testing Java 11, apparently now you have to make an Oracle account to download older versions of Java now. Now that is some major BS right there.

So I'm pretty much stuck between a rock and a hard place for now, one plugin needs Java 11 or higher, one needs 11 or older apparently, and I only have 13, and my old copy of 8 >_<

(No wonder they say 13 is an unlucky number)

**Comment by SeanOMik** [comment]
I don't remember having a Oracle account, but I may of already been logged into it. Just create a Oracle account and put in some bs company name etc

**Comment by Pecacheu** [comment]
Ah ha! Got a Linux installer for Java 11 from a mirror site. Seems like it's working smoothly for now.

Though I did notice one apparent bug where it seems like wild foxes run away from the player even while sneaking.

**Comment by SeanOMik** [comment]
Awesome, that's great that it's working. I added a notice on the SpigotMC page. I'm aware of the "bug". I thought that's how normal foxes act? I may add that feature though.
