### ISSUE TITLE
[Bug] Spamming bugs and crashing the server

### ISSUE THREAD

**Issue by GameKuchen** [SeanOMik/TamableFoxes#70]
**Describe the bug**
Spamming bugs and crashing the server

**To Reproduce**
Start server, wait a bit or have players joining.

**Expected behavior**
Not spam and not crashing the server

**Errors**
[17:56:26 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:56:26 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:56:26 WARN]:        at TamableFoxes_v2.2.2-SNAPSHOT.jar//net.seanomik.tamablefoxes.versions.version_1_18_R1.EntityTamableFox.fL(EntityTamableFox.java:177)
[17:56:26 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)

**Versions**
MC: 1.18.1
Java: 17

**Comment by SeanOMik** [comment]
Are you using Paper?

**Comment by GameKuchen** [comment]
Yes, i'am using Paper

**Comment by SeanOMik** [comment]
@GameKuchen Fixed in [latest release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.3-SNAPSHOT)
