### ISSUE TITLE
[Bug] Minecraft 1.18.2 support

### ISSUE THREAD

**Issue by Futodama** [SeanOMik/TamableFoxes#74]
initializing Tamablefoxes v2.2.3-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null
	at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:80) ~[TamableFoxes_v2.2.3-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.18.2.jar:git-Paper-222]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-222]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-222]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-222]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by SeanOMik** [comment]
@Futodama I forgot to say that I added 1.18.2 support in the [latest release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.4-SNAPSHOT), enjoy!
