### ISSUE TITLE
1.18.2 Error (Add Support)

### ISSUE THREAD

**Issue by PanHaskins** [SeanOMik/TamableFoxes#75]
[19:45:42 ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null initializing Tamablefoxes v2.2.3-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null
at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:80) ~[TamableFoxes_v2.2.3-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423) ~[purpur-1.18.2.jar:git-Purpur-1576]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[purpur-1.18.2.jar:git-Purpur-1576]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[purpur-1.18.2.jar:git-Purpur-1576]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1576]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by SeanOMik** [comment]
Implemented in the [latest release](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.4-SNAPSHOT), enjoy!
