### ISSUE TITLE
[Bug]  Kicks when trying to interact with a fox

### ISSUE THREAD

**Issue by Vinellon** [SeanOMik/TamableFoxes#79]
When I try to interact with a fox (tame/kill, etc.), an error appears (attached below).
it doesn't always happen, somehow every other time

```
[21:12:33 ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInUseEntity@1e086ca6 for Vinely[/176.193.177.244:63098]
java.lang.NullPointerException: Cannot invoke "net.seanomik.tamablefoxes.util.io.sqlite.SQLiteHandler.getConnection()" because "net.seanomik.tamablefoxes.util.io.sqlite.SQLiteHelper.sqLiteHandler" is null
        at net.seanomik.tamablefoxes.util.io.sqlite.SQLiteHelper.addPlayerFoxAmount(SQLiteHelper.java:101) ~[TamableFoxes_v2.2.4-SNAPSHOT.jar:?]
        at net.seanomik.tamablefoxes.versions.version_1_18_R2.EntityTamableFox.b(EntityTamableFox.java:430) ~[TamableFoxes_v2.2.4-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.Mob.interact(Mob.java:1258) ~[?:?]
        at net.minecraft.world.entity.player.Player.interactOn(Player.java:1097) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.performInteraction(ServerGamePacketListenerImpl.java:2506) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2525) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2467) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-290]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-290]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-290]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-290]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-290]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by SeanOMik** [comment]
What plugin version, game version, and spigot fork (spigot, paper, etc.) are you using?

**Comment by Vinellon** [comment]
> What plugin version, game version, and spigot fork (spigot, paper, etc.) are you using?

I'm using plugin 2.2.4-SNAPSHOT and paper-1.18.2-290

**Comment by SeanOMik** [comment]
I believe I fixed this. Could you try this version: [TamableFoxes_v2.2.5-SNAPSHOT.zip](https://github.com/SeanOMik/TamableFoxes/files/8647676/TamableFoxes_v2.2.5-SNAPSHOT.zip). The `.jar` is inside of the `.zip` since GitHub won't let me upload `.jar`s
