### ISSUE TITLE
"[ERROR]: Entity threw exception at..." spam console logs

### ISSUE THREAD

**Issue by Chevels** [SeanOMik/TamableFoxes#88]
Hello !
Since I upgraded my server to 1.19.2 (Paper) and installed the latest version of TamableFoxes (v2.2.7-SNAPSHOT) my console is regularly spammed with this error message :

> `>.... [16:57:41 ERROR]: Entity threw exception at Heavy:2908.0,72.0,757.0
> java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityLiving.co()" because the return value of "net.seanomik.tamablefoxes.versions.version_1_19_2_R1.EntityTamableFox.getOwner()" is null
> at net.seanomik.tamablefoxes.versions.version_1_19_2_R1.EntityTamableFox.a(EntityTamableFox.java:574) ~[TamableFoxes_v2.2.7-SNAPSHOT (1.19.2 & older).jar:?]
> at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
> at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:403) ~[?:?]
> at net.minecraft.world.entity.Mob.baseTick(Mob.java:329) ~[?:?]
> at net.minecraft.world.entity.Entity.tick(Entity.java:777) ~[paper-1.19.2.jar:git-Paper-138]
> at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2909) ~[?:?]
> at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
> at net.minecraft.world.entity.animal.Fox.tick(Fox.java:535) ~[?:?]
> at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1161) ~[?:?]
> at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
> at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:698) ~[?:?]
> at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-138]
> at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:678) ~[?:?]
> at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1554) ~[paper-1.19.2.jar:git-Paper-138]
> at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-138]
> at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-138]
> at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-138]
> at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-138]
> at java.lang.Thread.run(Thread.java:858) ~[?:?]`

The coordinates of the problematic entity are multiple, it is not a single problematic fox, but apparently all of them.

**Comment by smile-minecraft** [comment]
I got the same error:
```
[10:26:14 ERROR]: Entity threw exception at world:-79.35876636598854,159.0,-121.43432907024413
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityLiving.co()" because the return value of "net.seanomik.tamablefoxes.versions.version_1_19_2_R1.EntityTamableFox.getOwner()" is null
        at net.seanomik.tamablefoxes.versions.version_1_19_2_R1.EntityTamableFox.a(EntityTamableFox.java:574) ~[TamableFoxes_v2.2.7-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3370) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:634) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:60) ~[?:?]
        at net.minecraft.world.entity.animal.Fox.aiStep(Fox.java:233) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2950) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
        at net.minecraft.world.entity.animal.Fox.tick(Fox.java:535) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1156) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:693) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1554) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-132]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-132]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by SeanOMik** [comment]
I believe this was fixed in the [latest version](https://github.com/SeanOMik/TamableFoxes/releases/tag/2.2.9-SNAPSHOT).
