### ISSUE TITLE
Error on 1.19.3

### ISSUE THREAD

**Issue by legendofgow** [SeanOMik/TamableFoxes#95]
What does this error mean?

`
[18:55:31 ERROR]: Entity threw exception at world:-87.30000001192093,62.30000001192093,6727.300000011921
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityLiving.cs()" because the return value of "net.seanomik.tamablefoxes.versions.version_1_19_3_R1.EntityTamableFox.getOwner()" is null
        at net.seanomik.tamablefoxes.versions.version_1_19_3_R1.EntityTamableFox.a(EntityTamableFox.java:575) ~[TamableFoxes_v2.2.9-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1491) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:437) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:329) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:778) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2968) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
        at net.minecraft.world.entity.animal.Fox.tick(Fox.java:546) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1211) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:920) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by DexterSK** [comment]
yup same problem
