### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MinerCoffee** [SeanOMik/TamableFoxes#98]
**Describe the bug**

**To Reproduce**
1. Start server on 1.20.1
2 See error in console

**Expected behavior**
No console spam.

**Errors**
[12:02:42] [Server thread/ERROR]: [Tamablefoxes] Error initializing plugin 'TamableFoxes_v2.2.5-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.seanomik.tamablefoxes.util.NMSInterface.registerCustomFoxEntity()" because "this.nmsInterface" is null
	at net.seanomik.tamablefoxes.TamableFoxes.onLoad(TamableFoxes.java:86) ~[TamableFoxes_v2.2.5-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:444) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1995]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Versions**
MC: 1.20.1
Java: 17

**Additional context**

**Comment by SeanOMik** [comment]
Clone of #99
